### ISSUE TITLE
HOW TO stitch enhanced patches to single image? 

### ISSUE THREAD

**Issue by kirill-pinigin** [aiff22/DPED#20]
Please, tell me HOW TO stitch enhanced patches to single image?  What do you use to stitch enhanced patches to single image? Do you meet some problem with combining or stitching? Or May be some artifacts?

**Comment by aiff22** [comment]
@kirill-pinigin, you should pass the entire (full-resolution) image to the network instead of stitching the patches. Please note that the latter option will result in a corrupted image: instance normalization layers used in DPED network are leading to different brightness of the patches, and thus after combining them you will get an image with a checkerboard pattern.

**Comment by kirill-pinigin** [comment]
@aiff22  will it work if i replace instance_norm with batch_norm and retrain generator via your framework? Can I eliminate checkboard artefacts?
